<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateDistrictsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('districts', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('slug');
            $table->unsignedInteger('zone');
            $table->timestamps();
        });
        // Insert some stuff
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ازگل', 'slug' => 'ازگل', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اقدسیه', 'slug' => 'اقدسیه', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'الهيه', 'slug' => 'الهيه', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'امامزاده قاسم', 'slug' => 'امامزاده قاسم', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اوین', 'slug' => 'اوین', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'باغ فردوس', 'slug' => 'باغ فردوس', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تجریش', 'slug' => 'تجریش', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'جماران', 'slug' => 'جماران', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'چیذر', 'slug' => 'چیذر', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دارآباد', 'slug' => 'دارآباد', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دربند', 'slug' => 'دربند', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'درکه', 'slug' => 'درکه', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دزاشیب', 'slug' => 'دزاشیب', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'جوزستان', 'slug' => 'جوزستان', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'زعفرانیه', 'slug' => 'زعفرانیه', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سوهانک', 'slug' => 'سوهانک', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک نفت', 'slug' => 'شهرک نفت', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک محلاتی', 'slug' => 'شهرک محلاتی', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'فرمانیه', 'slug' => 'فرمانیه', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'فرشته', 'slug' => 'فرشته', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'قیطریه', 'slug' => 'قیطریه', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کاشانک', 'slug' => 'کاشانک', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کامرانیه', 'slug' => 'کامرانیه', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'محمودیه', 'slug' => 'محمودیه', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نیاوران', 'slug' => 'نیاوران', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ولنجک', 'slug' => 'ولنجک', 'zone' => 1 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'برق آلستوم', 'slug' => 'برق آلستوم', 'zone' => 2 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تهران ویلا', 'slug' => 'تهران ویلا', 'zone' => 2 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ستارخان', 'slug' => 'ستارخان', 'zone' => 2 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سعادت آباد', 'slug' => 'سعادت آباد', 'zone' => 2 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک غرب', 'slug' => 'شهرک غرب', 'zone' => 2 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک مخابرات', 'slug' => 'شهرک مخابرات', 'zone' => 2 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرآرا', 'slug' => 'شهرآرا', 'zone' => 2 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'صادقیه', 'slug' => 'صادقیه', 'zone' => 2 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'طرشت', 'slug' => 'طرشت', 'zone' => 2 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'فرحزاد', 'slug' => 'فرحزاد', 'zone' => 2 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'گیشا', 'slug' => 'گیشا', 'zone' => 2 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'همایون شهر', 'slug' => 'همایون شهر', 'zone' => 2 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مرزداران', 'slug' => 'مرزداران', 'zone' => 2 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اختیاریه', 'slug' => 'اختیاریه', 'zone' => 3 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'پاسداران', 'slug' => 'پاسداران', 'zone' => 3 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دروس', 'slug' => 'دروس', 'zone' => 3 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دولت', 'slug' => 'دولت', 'zone' => 3 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دیباجی', 'slug' => 'دیباجی', 'zone' => 3 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'جردن', 'slug' => 'جردن', 'zone' => 3 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ولیعصر', 'slug' => 'ولیعصر', 'zone' => 3 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سیدخندان', 'slug' => 'سیدخندان', 'zone' => 3 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ظفر', 'slug' => 'ظفر', 'zone' => 3 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'قلهک', 'slug' => 'قلهک', 'zone' => 3 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'میرداماد', 'slug' => 'میرداماد', 'zone' => 3 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ونک', 'slug' => 'ونک', 'zone' => 3 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بلوار پروین', 'slug' => 'بلوار پروین', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تهرانپارس', 'slug' => 'تهرانپارس', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'حکیمیه', 'slug' => 'حکیمیه', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سراج', 'slug' => 'سراج', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شمس آباد', 'slug' => 'شمس آباد', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مجیدیه', 'slug' => 'مجیدیه', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شمیران نو', 'slug' => 'شمیران نو', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'علم و صنعت', 'slug' => 'علم و صنعت', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'فرجام', 'slug' => 'فرجام', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'قنات کوثر', 'slug' => 'قنات کوثر', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'لویزان', 'slug' => 'لویزان', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شیان', 'slug' => 'شیان', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مهران', 'slug' => 'مهران', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نارمک', 'slug' => 'نارمک', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'هروی', 'slug' => 'هروی', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'هنگام', 'slug' => 'هنگام', 'zone' => 4 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'آيت الله كاشانی', 'slug' => 'آيت الله كاشانی', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اشرفی اصفهانی', 'slug' => 'اشرفی اصفهانی', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'باغ فیض', 'slug' => 'باغ فیض', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بلوار فردوس', 'slug' => 'بلوار فردوس', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'پونک', 'slug' => 'پونک', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'جنت آباد', 'slug' => 'جنت آباد', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'حصارک', 'slug' => 'حصارک', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سازمان برنامه', 'slug' => 'سازمان برنامه', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شاهین', 'slug' => 'شاهین', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهران', 'slug' => 'شهران', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرزيبا', 'slug' => 'شهرزيبا', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک آپادانا', 'slug' => 'شهرک آپادانا', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک اکباتان', 'slug' => 'شهرک اکباتان', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک اندیشه', 'slug' => 'شهرک اندیشه', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک پرواز', 'slug' => 'شهرک پرواز', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک کوهسار', 'slug' => 'شهرک کوهسار', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک نفت', 'slug' => 'شهرک نفت', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک والفجر', 'slug' => 'شهرک والفجر', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کنکوی', 'slug' => 'کنکوی', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ارمکوی', 'slug' => 'ارمکوی', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بیمه', 'slug' => 'بیمه', 'zone' => 5 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'آرژانتین', 'slug' => 'آرژانتین', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ساعی', 'slug' => 'ساعی', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'امیرآباد', 'slug' => 'امیرآباد', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ایرانشهر', 'slug' => 'ایرانشهر', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بهجت آباد', 'slug' => 'بهجت آباد', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'پارک لاله', 'slug' => 'پارک لاله', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'جنت', 'slug' => 'جنت', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'رفتگر', 'slug' => 'رفتگر', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'جمالزاده', 'slug' => 'جمالزاده', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دانشگاه تهران', 'slug' => 'دانشگاه تهران', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شریعتی', 'slug' => 'شریعتی', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شیراز', 'slug' => 'شیراز', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'عباس آباد', 'slug' => 'عباس آباد', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'فاطمی', 'slug' => 'فاطمی', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'قائم مقام', 'slug' => 'قائم مقام', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سنائی', 'slug' => 'سنائی', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'قزل قلعه', 'slug' => 'قزل قلعه', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کشاورز غربی', 'slug' => 'کشاورز غربی', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کریمخان', 'slug' => 'کریمخان', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'گاندی', 'slug' => 'گاندی', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'میدان جهاد', 'slug' => 'میدان جهاد', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'میدان ولیعصر', 'slug' => 'میدان ولیعصر', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نصرتی', 'slug' => 'نصرتی', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'وسف آباد ', 'slug' => 'وسف آباد ', 'zone' => 6 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اجاره دار', 'slug' => 'اجاره دار', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ارامنه', 'slug' => 'ارامنه', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'امجدیه', 'slug' => 'امجدیه', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'خاقانی', 'slug' => 'خاقانی', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'باغ صبا ، سهروردی', 'slug' => 'باغ صبا ، سهروردی', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بهار', 'slug' => 'بهار', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'حشمتیه', 'slug' => 'حشمتیه', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'خواجه نصیر', 'slug' => 'خواجه نصیر', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'حقوقی', 'slug' => 'حقوقی', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دبستان،مجیدیه', 'slug' => 'دبستان،مجیدیه', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سبلان', 'slug' => 'سبلان', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'عباس آباد،اندیشه', 'slug' => 'عباس آباد،اندیشه', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'قصر', 'slug' => 'قصر', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کاج', 'slug' => 'کاج', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کریمخان', 'slug' => 'کریمخان', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مطهری نامجو', 'slug' => 'مطهری نامجو', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نظام آباد', 'slug' => 'نظام آباد', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نیلوفر،شهید قندی', 'slug' => 'نیلوفر،شهید قندی', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'هفت تیر ', 'slug' => 'هفت تیر ', 'zone' => 7 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تسلیحات', 'slug' => 'تسلیحات', 'zone' => 8 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تهران پارس', 'slug' => 'تهران پارس', 'zone' => 8 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دردشت', 'slug' => 'دردشت', 'zone' => 8 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'زرکش', 'slug' => 'زرکش', 'zone' => 8 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'فدک', 'slug' => 'فدک', 'zone' => 8 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کرمان', 'slug' => 'کرمان', 'zone' => 8 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'لشکر', 'slug' => 'لشکر', 'zone' => 8 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مجیدیه جنوبی', 'slug' => 'مجیدیه جنوبی', 'zone' => 8 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مدائن', 'slug' => 'مدائن', 'zone' => 8 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نارمک', 'slug' => 'نارمک', 'zone' => 8 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'وحیدیه', 'slug' => 'وحیدیه', 'zone' => 8 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'هفت حوض ', 'slug' => 'هفت حوض ', 'zone' => 8 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'استاد معین', 'slug' => 'استاد معین', 'zone' => 9 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'امامزاده عبدالله', 'slug' => 'امامزاده عبدالله', 'zone' => 9 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دکتر هوشیار', 'slug' => 'دکتر هوشیار', 'zone' => 9 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سرآسیاب، مهرآباد', 'slug' => 'سرآسیاب، مهرآباد', 'zone' => 9 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شمشیری', 'slug' => 'شمشیری', 'zone' => 9 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهید دستغیب', 'slug' => 'شهید دستغیب', 'zone' => 9 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'فتح', 'slug' => 'فتح', 'zone' => 9 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'صنعتی', 'slug' => 'صنعتی', 'zone' => 9 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'فرودگاه مهرآباد جنوبی ', 'slug' => 'فرودگاه مهرآباد جنوبی ', 'zone' => 9 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بریانک', 'slug' => 'بریانک', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سلیمانی تیموری', 'slug' => 'سلیمانی تیموری', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شبیری جی، هفت چنار', 'slug' => 'شبیری جی، هفت چنار', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سلسبیل جنوبی', 'slug' => 'سلسبیل جنوبی', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کارون جنوبی', 'slug' => 'کارون جنوبی', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'هاشمی', 'slug' => 'هاشمی', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'زنجان جنوبی', 'slug' => 'زنجان جنوبی', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سلسبیل شمالی', 'slug' => 'سلسبیل شمالی', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کارون شمالی، ', 'slug' => 'کارون شمالی، ', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'آذربایجان', 'slug' => 'آذربایجان', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'آزادی', 'slug' => 'آزادی', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'امام خمینی', 'slug' => 'امام خمینی', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'جیحون', 'slug' => 'جیحون', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'حسام الدین', 'slug' => 'حسام الدین', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'خوش', 'slug' => 'خوش', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دامپزشکی', 'slug' => 'دامپزشکی', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'رودکی', 'slug' => 'رودکی', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سینا', 'slug' => 'سینا', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'قصرالدشت', 'slug' => 'قصرالدشت', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مالک اشتر', 'slug' => 'مالک اشتر', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نواب', 'slug' => 'نواب', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کارون', 'slug' => 'کارون', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کمیل', 'slug' => 'کمیل', 'zone' => 10 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شیخ هادی', 'slug' => 'شیخ هادی', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'انقلاب', 'slug' => 'انقلاب', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'امیریه ( فرهنگ )', 'slug' => 'امیریه ( فرهنگ )', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'فروزش', 'slug' => 'فروزش', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'قلمستان', 'slug' => 'قلمستان', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'منیریه', 'slug' => 'منیریه', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'حشمت الدوله – جمالزاده', 'slug' => 'حشمت الدوله – جمالزاده', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اسکندری', 'slug' => 'اسکندری', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دخانیات', 'slug' => 'دخانیات', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مخصوص', 'slug' => 'مخصوص', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'جمهوری', 'slug' => 'جمهوری', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'حر', 'slug' => 'حر', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'انبار نفت', 'slug' => 'انبار نفت', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'آگاهی', 'slug' => 'آگاهی', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'راه آهن', 'slug' => 'راه آهن', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'عباسی', 'slug' => 'عباسی', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'هلال احمر', 'slug' => 'هلال احمر', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ابوسعید', 'slug' => 'ابوسعید', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اسکندری جنوبی', 'slug' => 'اسکندری جنوبی', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'پاستور', 'slug' => 'پاستور', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'حسن آباد', 'slug' => 'حسن آباد', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'گمرک', 'slug' => 'گمرک', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'وحدت اسلامی', 'slug' => 'وحدت اسلامی', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ولیعصر', 'slug' => 'ولیعصر', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کارگر جنوبی', 'slug' => 'کارگر جنوبی', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کاشان', 'slug' => 'کاشان', 'zone' => 11 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بهارستان', 'slug' => 'بهارستان', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'فردوسی', 'slug' => 'فردوسی', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'امامزاده یحیی', 'slug' => 'امامزاده یحیی', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'پامنار', 'slug' => 'پامنار', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بازار', 'slug' => 'بازار', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سنگلج', 'slug' => 'سنگلج', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تختی', 'slug' => 'تختی', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'هرندی', 'slug' => 'هرندی', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'آبشار', 'slug' => 'آبشار', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'قیام', 'slug' => 'قیام', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کوثر', 'slug' => 'کوثر', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ایران', 'slug' => 'ایران', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دروازه شمیران', 'slug' => 'دروازه شمیران', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'امین حضور', 'slug' => 'امین حضور', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'پانزده خرداد', 'slug' => 'پانزده خرداد', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'پیچ شمیران', 'slug' => 'پیچ شمیران', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'خراسان', 'slug' => 'خراسان', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ری', 'slug' => 'ری', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سعدی', 'slug' => 'سعدی', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'لاله زارنو', 'slug' => 'لاله زارنو', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مولوی', 'slug' => 'مولوی', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'میدان قیام', 'slug' => 'میدان قیام', 'zone' => 12 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'صفا', 'slug' => 'صفا', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهید اسدی', 'slug' => 'شهید اسدی', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'زاهد گیلانی', 'slug' => 'زاهد گیلانی', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اشراقی', 'slug' => 'اشراقی', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دهقان', 'slug' => 'دهقان', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نیروی هوایی', 'slug' => 'نیروی هوایی', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'پیروزی', 'slug' => 'پیروزی', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'حافظیه', 'slug' => 'حافظیه', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'امامت', 'slug' => 'امامت', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شورا', 'slug' => 'شورا', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'آشتیانی', 'slug' => 'آشتیانی', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'زینبیه', 'slug' => 'زینبیه', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سرخه حصار، ', 'slug' => 'سرخه حصار، ', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تهران نو', 'slug' => 'تهران نو', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دماوند', 'slug' => 'دماوند', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نیرو هوایی', 'slug' => 'نیرو هوایی', 'zone' => 13 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شکوفه', 'slug' => 'شکوفه', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'چهارصد دستگاه', 'slug' => 'چهارصد دستگاه', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'جابری', 'slug' => 'جابری', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دژکام', 'slug' => 'دژکام', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شاهین', 'slug' => 'شاهین', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مینای شمالی', 'slug' => 'مینای شمالی', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نیکنام', 'slug' => 'نیکنام', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'آهنگران', 'slug' => 'آهنگران', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بروجردی', 'slug' => 'بروجردی', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'صد دستگاه', 'slug' => 'صد دستگاه', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'فرزانه', 'slug' => 'فرزانه', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سر آسیب دولاب،', 'slug' => 'سر آسیب دولاب،', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شیوا', 'slug' => 'شیوا', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نبی اکرم (ص)', 'slug' => 'نبی اکرم (ص)', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرابی ( قیام )', 'slug' => 'شهرابی ( قیام )', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شکیب', 'slug' => 'شکیب', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'پرستار', 'slug' => 'پرستار', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سیزده آبان', 'slug' => 'سیزده آبان', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ابوذر', 'slug' => 'ابوذر', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تاکسیرانی', 'slug' => 'تاکسیرانی', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مینای جنوبی', 'slug' => 'مینای جنوبی', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دولاب', 'slug' => 'دولاب', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'خاوران', 'slug' => 'خاوران', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'آهنگ شرقی', 'slug' => 'آهنگ شرقی', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'آهنگ', 'slug' => 'آهنگ', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'قصر فیروزه', 'slug' => 'قصر فیروزه', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اتوبان محلاتی', 'slug' => 'اتوبان محلاتی', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'افراسیابی شمالی', 'slug' => 'افراسیابی شمالی', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اندرزگو', 'slug' => 'اندرزگو', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'پاسدارگمنام', 'slug' => 'پاسدارگمنام', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهید محلاتی', 'slug' => 'شهید محلاتی', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'فلاح', 'slug' => 'فلاح', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نبرد', 'slug' => 'نبرد', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'هفده شهریور', 'slug' => 'هفده شهریور', 'zone' => 14 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مظاهری', 'slug' => 'مظاهری', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مینابی', 'slug' => 'مینابی', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بیسیم', 'slug' => 'بیسیم', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شوش', 'slug' => 'شوش', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'طیب', 'slug' => 'طیب', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مطهری', 'slug' => 'مطهری', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ابوذر', 'slug' => 'ابوذر', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'هاشم آباد', 'slug' => 'هاشم آباد', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اتابک', 'slug' => 'اتابک', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهید بروجردی', 'slug' => 'شهید بروجردی', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کیانشهر شمالی', 'slug' => 'کیانشهر شمالی', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کیانشهر جنوبی', 'slug' => 'کیانشهر جنوبی', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'رضویه', 'slug' => 'رضویه', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مشیریه', 'slug' => 'مشیریه', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'افسریه شمالی', 'slug' => 'افسریه شمالی', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'افسریه جنوبی', 'slug' => 'افسریه جنوبی', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مسعودیه', 'slug' => 'مسعودیه', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'والفجر', 'slug' => 'والفجر', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'قیامدشت', 'slug' => 'قیامدشت', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'خاورشهر', 'slug' => 'خاورشهر', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'آهنگ', 'slug' => 'آهنگ', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اتوبان بعثت', 'slug' => 'اتوبان بعثت', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'افسریه', 'slug' => 'افسریه', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'خاوران', 'slug' => 'خاوران', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مشیریه', 'slug' => 'مشیریه', 'zone' => 15 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'جوادیه', 'slug' => 'جوادیه', 'zone' => 16 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نازی آباد', 'slug' => 'نازی آباد', 'zone' => 16 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'خزانه', 'slug' => 'خزانه', 'zone' => 16 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک بعثت', 'slug' => 'شهرک بعثت', 'zone' => 16 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'علی آباد شمالی', 'slug' => 'علی آباد شمالی', 'zone' => 16 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'یاخچی آباد', 'slug' => 'یاخچی آباد', 'zone' => 16 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'چهارصد دستگاه', 'slug' => 'چهارصد دستگاه', 'zone' => 16 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تختی', 'slug' => 'تختی', 'zone' => 16 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'علی آباد جنوبی', 'slug' => 'علی آباد جنوبی', 'zone' => 16 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'باغ آذری', 'slug' => 'باغ آذری', 'zone' => 16 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'راه آهن', 'slug' => 'راه آهن', 'zone' => 16 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'رجایی', 'slug' => 'رجایی', 'zone' => 16 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'هلال احمر', 'slug' => 'هلال احمر', 'zone' => 16 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'یاخچی آباد ', 'slug' => 'یاخچی آباد ', 'zone' => 16 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ابوذر غربی', 'slug' => 'ابوذر غربی', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'آذری', 'slug' => 'آذری', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'امامزاده حسن', 'slug' => 'امامزاده حسن', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'یافت آباد', 'slug' => 'یافت آباد', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'جلیلی', 'slug' => 'جلیلی', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'زهتابی', 'slug' => 'زهتابی', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'زمزم', 'slug' => 'زمزم', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سجاد', 'slug' => 'سجاد', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'گلچین', 'slug' => 'گلچین', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'وصفنارد', 'slug' => 'وصفنارد', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ابوذر شرقی', 'slug' => 'ابوذر شرقی', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'باغ خزانه', 'slug' => 'باغ خزانه', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بلورسازی', 'slug' => 'بلورسازی', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'مقدم', 'slug' => 'مقدم', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ابوذر', 'slug' => 'ابوذر', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'امام زاده حسن', 'slug' => 'امام زاده حسن', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'قزوین', 'slug' => 'قزوین', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'قلعه مرغی', 'slug' => 'قلعه مرغی', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'میدان بهاران', 'slug' => 'میدان بهاران', 'zone' => 17 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'فردوس', 'slug' => 'فردوس', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تولیدارو', 'slug' => 'تولیدارو', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بهداشت', 'slug' => 'بهداشت', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ولیعصر شمالی', 'slug' => 'ولیعصر شمالی', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'رجائی', 'slug' => 'رجائی', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ولیعصر جنوبی', 'slug' => 'ولیعصر جنوبی', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'صادقیه', 'slug' => 'صادقیه', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'صاحب الزمان', 'slug' => 'صاحب الزمان', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'یافت آباد جنوبی', 'slug' => 'یافت آباد جنوبی', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'یافت آباد شمالی', 'slug' => 'یافت آباد شمالی', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شاد آباد', 'slug' => 'شاد آباد', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'هفده شهریور', 'slug' => 'هفده شهریور', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'امام خمینی', 'slug' => 'امام خمینی', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شمس آباد', 'slug' => 'شمس آباد', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'خلیج فارس شمالی', 'slug' => 'خلیج فارس شمالی', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'خلیج فارس جنوبی', 'slug' => 'خلیج فارس جنوبی', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اتوبان آزادگان', 'slug' => 'اتوبان آزادگان', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'خلیج فارس', 'slug' => 'خلیج فارس', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سعید آباد', 'slug' => 'سعید آباد', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک صاحب الزمان', 'slug' => 'شهرک صاحب الزمان', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک ولیعصر', 'slug' => 'شهرک ولیعصر', 'zone' => 18 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'خانی آباد نو شمالی', 'slug' => 'خانی آباد نو شمالی', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اسفندیاری و بستان', 'slug' => 'اسفندیاری و بستان', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بهمنیار', 'slug' => 'بهمنیار', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'خانی آباد نو جنوبی', 'slug' => 'خانی آباد نو جنوبی', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شریعتی جنوبی', 'slug' => 'شریعتی جنوبی', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شریعتی شمالی', 'slug' => 'شریعتی شمالی', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شکوفه جنوبی', 'slug' => 'شکوفه جنوبی', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شکوفه شمالی', 'slug' => 'شکوفه شمالی', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نعمت آباد', 'slug' => 'نعمت آباد', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دولت خواه', 'slug' => 'دولت خواه', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اسماعیل آباد', 'slug' => 'اسماعیل آباد', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهید کاظمی', 'slug' => 'شهید کاظمی', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'رسالت', 'slug' => 'رسالت', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'خانی آباد نو', 'slug' => 'خانی آباد نو', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'عبدل آباد', 'slug' => 'عبدل آباد', 'zone' => 19 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => ' اقدسیه', 'slug' => ' اقدسیه', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'صفائیه', 'slug' => 'صفائیه', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ظهیر آباد', 'slug' => 'ظهیر آباد', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'غیوری', 'slug' => 'غیوری', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'جوانمرد', 'slug' => 'جوانمرد', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'حمزه آباد', 'slug' => 'حمزه آباد', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دیلمان', 'slug' => 'دیلمان', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'فیروزآبادی', 'slug' => 'فیروزآبادی', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'منصوریه', 'slug' => 'منصوریه', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => '۱۳آبان', 'slug' => '۱۳آبان', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دولت اباد', 'slug' => 'دولت اباد', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهادت', 'slug' => 'شهادت', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'استخر', 'slug' => 'استخر', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بهشتی', 'slug' => 'بهشتی', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'سرتخت', 'slug' => 'سرتخت', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'علائین', 'slug' => 'علائین', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نفر آباد', 'slug' => 'نفر آباد', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ولی آباد', 'slug' => 'ولی آباد', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'امین آباد', 'slug' => 'امین آباد', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تقی آباد', 'slug' => 'تقی آباد', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'نظامی', 'slug' => 'نظامی', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'عباس آباد', 'slug' => 'عباس آباد', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'کهریزک', 'slug' => 'کهریزک', 'zone' => 20 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => ' شهرک دریا', 'slug' => ' شهرک دریا', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تهرانسر غربی', 'slug' => 'تهرانسر غربی', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تهرانسر شرقی', 'slug' => 'تهرانسر شرقی', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'باشگاه نفت', 'slug' => 'باشگاه نفت', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تهرانسر مرکزی', 'slug' => 'تهرانسر مرکزی', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک پاسداران', 'slug' => 'شهرک پاسداران', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تهرانسر شمالی', 'slug' => 'تهرانسر شمالی', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک آزادی', 'slug' => 'شهرک آزادی', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک فرهنگیان', 'slug' => 'شهرک فرهنگیان', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک استقلال', 'slug' => 'شهرک استقلال', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک دانشگاه', 'slug' => 'شهرک دانشگاه', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'چیتگر شمالی', 'slug' => 'چیتگر شمالی', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'چیتگر جنوبی (شهرک ۲۲ بهمن)', 'slug' => 'چیتگر جنوبی (شهرک ۲۲ بهمن)', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'ویلا شهر', 'slug' => 'ویلا شهر', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'وردآورد', 'slug' => 'وردآورد', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک غزالی', 'slug' => 'شهرک غزالی', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک شهرداری', 'slug' => 'شهرک شهرداری', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'اتوبان تهران کرج', 'slug' => 'اتوبان تهران کرج', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'بزرگراه فتح', 'slug' => 'بزرگراه فتح', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'تهرانسر', 'slug' => 'تهرانسر', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک ۲۲بهمن', 'slug' => 'شهرک ۲۲بهمن', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک دانشگاه شریف', 'slug' => 'شهرک دانشگاه شریف', 'zone' => 21 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دهکده المپیک', 'slug' => 'دهکده المپیک', 'zone' => 22 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'زیبا دشت بالا', 'slug' => 'زیبا دشت بالا', 'zone' => 22 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'گلستان شرقی', 'slug' => 'گلستان شرقی', 'zone' => 22 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'زیبادشت پائین', 'slug' => 'زیبادشت پائین', 'zone' => 22 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شریف', 'slug' => 'شریف', 'zone' => 22 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'گلستان غربی', 'slug' => 'گلستان غربی', 'zone' => 22 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'امید – دژبان', 'slug' => 'امید – دژبان', 'zone' => 22 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهید باقری', 'slug' => 'شهید باقری', 'zone' => 22 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'آزادشهر', 'slug' => 'آزادشهر', 'zone' => 22 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'پیکان شهر', 'slug' => 'پیکان شهر', 'zone' => 22 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'دریاچه چیتگر', 'slug' => 'دریاچه چیتگر', 'zone' => 22 ] );
        \Illuminate\Support\Facades\DB::table('districts')->insert([ 'name' => 'شهرک راه آهن – شهرک گلستان', 'slug' => 'شهرک راه آهن – شهرک گلستان', 'zone' => 22 ] );
    }


    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('districts');
    }
}
